{% set version = "2.0-4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-intergraph
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/intergraph_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/intergraph/intergraph_{{ version }}.tar.gz
  sha256: 585f2f9fa92aa52022dfdcbe597a3654099ca63c1d4110a0f8e895fa32fc59c9

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:

  host:
    - r-base
    - r-igraph >=0.6_0
    - r-network >=1.4_1_1
  run:
    - r-base
    - r-igraph >=0.6_0
    - r-network >=1.4_1_1

test:
  commands:
    - $R -e "library('intergraph')"           # [not win]
    - "\"%R%\" -e \"library('intergraph')\""  # [win]

about:
  home: http://mbojan.github.io/intergraph
  license: GPL-3.0-only
  summary: 'Functions implemented in this package allow to coerce (i.e. convert) network data between classes provided by other R packages. Currently supported classes are those defined in packages: network and igraph.'
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: intergraph
# Type: Package
# Title: Coercion Routines for Network Data Objects
# Version: 2.0-2
# Date: 2015-06-29
# Author: Michal Bojanowski
# Maintainer: Michal Bojanowski <m.bojanowski@icm.edu.pl>
# Description: Functions implemented in this package allow to coerce (i.e. convert) network data between classes provided by other R packages. Currently supported classes are those defined in packages: network and igraph.
# URL: http://mbojan.github.io/intergraph
# Imports: network (>= 1.4-1-1), igraph (>= 0.6-0), utils
# Suggests: testthat, roxygen2, knitr
# VignetteBuilder: knitr
# License: GPL-3
# LazyLoad: yes
# LazyData: yes
# NeedsCompilation: no
# Packaged: 2016-12-05 14:59:49 UTC; hornik
# Repository: CRAN
# Date/Publication: 2016-12-05 18:28:47
